version: '3'

services:
  app:
    container_name: restapi-uvicorn
    build: ./app
    env_file:
      - ".env"
    networks:
      - nginx_network

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge